matrix:
  include:
    - language: node_js
      os:
        - linux
      #- osx
      #- windows
      node_js:
        - 10
      before_script:
        - cd ts
      script:
        - yarn install
        - npm test

#    - language: rust
#      os:
#        - linux
#      rust:
#        - stable
#      before_script:
#        - cd rs
#      script:
#        - cargo build
#        - cargo test

notifications:
  email: false
