[package]
name = "swf-renderer"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]

[lib]
name = "swf_renderer"
path = "src/lib.rs"

[[bin]]
name = "swf-renderer"
path = "src/main.rs"

[dependencies]
gfx = "^0.16.1"
piston = "0.32.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.37.0"
piston2d-opengl_graphics = "0.44.0"
