[package]
name = "swf-renderer"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "SWF renderer"
documentation = "https://github.com/open-flash/swf-renderer"
homepage = "https://github.com/open-flash/swf-renderer"
repository = "https://github.com/open-flash/swf-renderer"
readme = "./README.md"
keywords = ["renderer", "swf", "flash", "gfx"]
license = "AGPL-3.0-or-later"
edition = "2018"

[lib]
name = "swf_renderer"
path = "src/lib.rs"

[[bin]]
name = "swf-renderer"
path = "src/main.rs"

[dependencies]
lyon = "^0.13.1"
shaderc = "^0.3.16"
swf-tree = "^0.4.1"
gfx-hal = "^0.1.0"
gfx-backend-vulkan = "^0.1.0"
env_logger = "^0.6.1"
nalgebra-glm = "^0.4.0"

[dev-dependencies]
genmesh = "0.6"
nalgebra = "0.16"
failure = "0.1"
lazy_static = "1.0"
winit = "0.18"
palette = "0.4"
rand = "0.6"
