[package]
name = "swf-renderer-bin"
version = "0.0.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Abstract Syntax Tree (AST) for SWF files"
documentation = "https://github.com/open-flash/swf-renderer"
homepage = "https://github.com/open-flash/swf-renderer"
repository = "https://github.com/open-flash/swf-renderer"
readme = "../README.md"
keywords = ["swf", "renderer"]
license = "AGPL-3.0-or-later"
edition = "2018"

[[bin]]
name = "swf-renderer"
path = "src/main.rs"

[dependencies]
env_logger = "^0.6.2"
gfx-hal = {git = "https://github.com/gfx-rs/gfx.git", rev="8c8c3cd0da39fc64aeac6fb1bb5d5864bb33d2df"}
serde_json = "^1.0.41"
swf-renderer = { path = "../" }
swf-tree = "^0.8.0"
winit = "^0.20.0-alpha3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gfx-backend-vulkan = {git = "https://github.com/gfx-rs/gfx.git", rev="8c8c3cd0da39fc64aeac6fb1bb5d5864bb33d2df", features = ["x11"]}
